# Generated by Django 2.0.2 on 2018-03-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('uid', models.AutoField(help_text='User identifier.', primary_key=True, serialize=False)),
                ('usertype', models.IntegerField(help_text='User type (1 = user, 2 = admin).')),
                ('firstname', models.CharField(help_text='First name.', max_length=100)),
                ('lastname', models.CharField(help_text='Last name.', max_length=100)),
                ('username', models.CharField(help_text='Username.', max_length=30)),
                ('password', models.CharField(help_text='Hashed user password.', max_length=255)),
                ('email', models.EmailField(help_text='User email.', max_length=254)),
                ('notification', models.BooleanField(help_text='Receive email notifications?')),
                ('pronoun', models.CharField(help_text='User pronouns.', max_length=30)),
                ('phone', models.IntegerField(help_text='User phone number.')),
                ('overtime', models.BooleanField(help_text='Work overtime?')),
            ],
        ),
    ]
