# Generated by Django 2.0.2 on 2018-03-26 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloq', '0003_auto_20180320_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+1 (888) 888-8888', help_text='User phone number.', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+1 (888) 888-8888'.", regex='^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]\\d{3}[\\s.-]\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='pronoun',
            field=models.CharField(blank=True, default='they/them/theirs', help_text='User pronouns.', max_length=30),
        ),
    ]
