# Generated by Django 2.0.2 on 2018-03-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloq', '0003_auto_20180320_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pronoun',
            field=models.CharField(blank=True, default='they/them/theirs', help_text='User pronouns.', max_length=30),
        ),
    ]
