# Generated by Django 2.0.2 on 2018-04-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloq', '0004_auto_20180326_1755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='usertype',
            field=models.IntegerField(help_text='Viewable by (1 = all users, 2 = admins only)'),
        ),
        migrations.AlterField(
            model_name='time',
            name='timetype',
            field=models.IntegerField(help_text='Time type (1 = punch in, 2 = punch out, 3 = shift, 4 = unavailable, 5 = request)'),
        ),
    ]
