# Generated by Django 2.0.2 on 2018-03-26 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloq', '0005_auto_20180326_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+1-888-888-8888', help_text='User phone number.', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+9-999-999-9999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{1,5}-\\d{1,5}-\\d{1,5}$')]),
        ),
    ]
