# Generated by Django 2.0.2 on 2018-04-15 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloq', '0005_auto_20180415_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('uid', models.AutoField(help_text='User identifier.', primary_key=True, serialize=False)),
                ('usertype', models.IntegerField(help_text='User type (1 = user, 2 = admin).')),
                ('firstname', models.CharField(help_text='First name.', max_length=100)),
                ('lastname', models.CharField(help_text='Last name.', max_length=100)),
                ('username', models.CharField(help_text='Username.', max_length=30)),
                ('password', models.CharField(help_text='Hashed user password.', max_length=255)),
                ('email', models.EmailField(help_text='User email.', max_length=254)),
                ('notification', models.BooleanField(help_text='Receive email notifications?')),
                ('pronoun', models.CharField(blank=True, default='they/them/theirs', help_text='User pronouns.', max_length=30)),
                ('phone', models.CharField(default='+1 (888) 888-8888', help_text='User phone number.', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+1 (888) 888-8888'.", regex='^(\\+\\d{1,2}\\s)?\\(?\\d{3}\\)?[\\s.-]\\d{3}[\\s.-]\\d{4}$')])),
                ('overtime', models.BooleanField(help_text='Work overtime?')),
            ],
        ),
    ]
