# Generated by Django 2.0.2 on 2018-04-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cloq', '0006_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
