# Generated by Django 2.0.2 on 2018-04-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cloq', '0007_remove_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='test', help_text='Hashed user password.', max_length=255),
            preserve_default=False,
        ),
    ]
